### ISSUE TITLE
Omega warhead detonation

### ISSUE THREAD

**Issue by 28858741** [ClaudioPanConQueso/BetterOmegaWarheadPlugin#2]
Hello, can you add a command to stop the detonation of Omega nuclear bomb? I see that your code has stopped detonating, but it has not been actually referenced in the game, and some players have not died after the countdown. Please repair it

**Comment by 28858741** [comment]
Another bug is that Omega may detonate at the beginning of the next round if the game ends during the Omega explosion

**Comment by ClaudioPanConQueso** [comment]
I will try to add a command to stop Omega warhead. And to avoid detonating in next round, don't turn off the round lock

**Comment by ClaudioPanConQueso** [comment]
fixed
