### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by DeaNo409** [ClaudioPanConQueso/BetterOmegaWarheadPlugin#4]
i added it to my Plugin Folder, but it didnt appear anywhere (not in config or ingame) what do you need for it? synapse or exiled?

**Comment by DeaNo409** [comment]
or any other, but i need this for my german community

**Comment by DeaNo409** [comment]
if you want you can write me on discord or something DeaNo#3925 so i can help me or something ;)

**Comment by ClaudioPanConQueso** [comment]
Check Discord DM
